config/routes.rb
Medicallapp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  root to: 'physician#index'
  get 'home' => 'physician#index'
  get 'medicine' => 'medicine#drug_list', as: 'drug_list'
  get 'session/:medical_session/medicine/:id' => 'medicine#drug_indication'
  get 'session/:medical_session/medicine/:id/education' => 'medicine#drug_education'
  post 'session/new' => 'medicalsession#new', as: 'new_session'
  get 'session/:medical_session/start_time' => 'medicalsession#start_time', as: 'start_time'
  get 'session/:medical_session/stop_time' => 'medicalsession#stop_time', as: 'stop_time'

  post 'indication/:id' => 'indication#choose_indication'
  post 'medicine/:id/final_indication' => 'medicine#drug_final_indication', as: 'show_final_indication'

  get 'show_import' => 'physician#show_import'
  post 'import' => 'medicine#import'
   resources :medicine do
     collection { post :import }
   end

end

app/models/medicine.rb
class Medicine < ActiveRecord::Base
  attr_accessible :drug_name, :brand
  validates :drug_name, presence: true
  validates :brand, presence: true
  has_many :education
  has_many :indication
  has_many :final_indication
  has_many :other_education
  has_many :medical_session_medicines, foreign_key: "medicine_id"
  has_many :medical_sessions, through: :medical_session_medicines

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      medicine = find_by_id(row["id"]) || Medicine.new
      medicine.attributes = row.to_hash.slice(*accessible_attributes)
      medicine.save!
      fdas = row.to_hash.slice("fda_1", "fda_2", "fda_3", "fda_4", "fda_5")
      for fda in fdas
        if fda[1].present?
          indication =  Indication.new
          indication.update_attributes(content:fda[1])
          indication.update_attributes(medicine_id:medicine.id)
        end
      end
      edus = row.to_hash.slice("edu_1", "edu_2", "edu_3", "edu_4", "edu_5")
      for edu in edus
        if edu[1].present?
          education =  Education.new
          education.update_attributes(content:edu[1])
          education.update_attributes(medicine_id:medicine.id)
        end
      end
      other_edu = row.to_hash.slice("other_edu")
      if other_edu.first[1].present?
        other = OtherEducation.new
        other.update_attributes(content:other_edu.first[1])
        other.update_attributes(medicine_id:medicine.id)
      end
    end
  end

  # alternative to read different files
# def self.import(file)
#   spreadsheet = open_spreadsheet(file)
#   debugger
#   header = spreadsheet.row(1)
#   (2..spreadsheet.last_row).each do |i|
#     row = Hash[[header, spreadsheet.row(i)].transpose]
#     medicine = find_by_id(row["id"]) || new
#     medicine.attributes = row.to_hash.slice(*accessible_attributes)
#     medicine.save!
#   end
# end

# def self.open_spreadsheet(file)
#   case File.extname(file.original_filename)
#   when ".csv" then Csv.new(file.path, nil, :ignore)
#   when ".xls" then Excel.new(file.path, nil, :ignore)
#   when ".xlsx" then Excelx.new(file.path, nil, :ignore)
#   else raise "Unknown file type: #{file.original_filename}"
#   end
# end
end

app/controllers/medicine_controller.rb
class MedicineController < ApplicationController
  include MedicineHelper

  def drug_list
  end

  def drug_indication
    @session = MedicalSession.find_by_id(params[:medical_session])
    @drug = Medicine.find_by_id(params[:id])
    @indication = @drug.indication.all
  end

  def drug_education
    FinalIndication.choose(params)
    @session = MedicalSession.find_by_id(params[:medical_session])
    @drug = Medicine.find_by_id(params[:id])
    @next_drug = @session.next_drug(@drug)

    @indication = @drug.indication.all
    @education = @drug.education.all
    @other_education = @drug.other_education.all
  end

  def drug_final_indication
  end

  def show_import
  end

  def import
    unless params[:file]
      redirect_to show_import_url, notice: "Please select file"
      return
    end
    clear_database(Medicine)
    Medicine.import(params[:file])
    redirect_to drug_list_path, notice: "File imported"
  end

  #only use for P&T users
# def show_final_indication
#   @drug = Medicine.find(params[:id])
#   if @drug.final_indication.count != 0
#     @final_indication = @drug.final_indication.all
#     render 'drug_final_indication'
#   else
#     @indication = @drug.indication.all
#   end
# end


end

app/helpers/medicine_helper.rb
module MedicineHelper
  def clear_database(model)
    model ? model.delete_all : nil
  end
end

app/views/medicine/drug_education.html.erb
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left" href="medicine">
    <span class="icon icon-left-nav"></span>
    <%= link_to "Back", action: "drug_indication", medical_session: params[:medical_session] %>
  </button>
  <button class="btn btn-link btn-nav pull-right">
    <% if !@next_drug.nil? then %>
      <%= link_to "Next Drug", action: "drug_education", medical_session: params[:medical_session], id: @next_drug.id %>
    <% else %>
      <%= link_to "Medicine List", drug_list_path %>
    <% end %>
    <span class="icon icon-right-nav"></span>
  </button>

  <h1 class="title">Generic Drug Name: <%= @drug.drug_name %></h1>
</header>

<div class="content">
    <button class="btn btn-block">Brand Drug Name: <%= @drug.brand %></button>
    <h5 align="middle" > Indications </h1>
    <ul class="table-view">
      <% for item in @indication %>
          <li class="table-view-cell media">
            <img class="media-object pull-left" src="http://placehold.it/42x42">
            <div class="media-body">
               <%= item.content%>
            </div> </li>
      <% end %>
    </ul>
    <h5 align="middle" > Education points </h1>
    <ul class="table-view">
      <% for item in @education %>
      <li class="table-view-cell media">
        <img class="media-object pull-left" src="http://placehold.it/42x42">
        <div class="media-body">
           <%= item.content %>
        </div>
      </li>
      <% end %>
    </ul>
    <% if !@other_education.empty? then %>
      <h5 align="middle"> Other education points </h1>
    <% end %>
    <ul class="table-view">
      <% for item in @other_education %>
      <li class="table-view-cell media">
        <img class="media-object pull-left" src="http://placehold.it/42x42">
        <div class="media-body">
           <%= item.content %>
        </div>
      </li>
      <% end %>
    <% if !@session.started? then %>
      <button id="start_time" type="submit" class="btn btn-block">Start timing the education time</button>
      <button id="stop_time" type="submit" class="btn btn-block hidden">Stop timing the education time</button>
    <% elsif @session.started? && !@session.ended? %>
      <button id="stop_time" type="submit" class="btn btn-block">Stop timing the education time</button>
    <% end %>
    </ul>
  </div>
  <%= render partial: "layouts/navigation" %>
<script>
  $("#start_time").click(function(event){
    alert("Great! Time recorded!");
    var session_id = "<%=params[:medical_session]%>";
    $.get("/session/" + session_id + "/start_time");
    $("#start_time").hide();
    $("#stop_time").removeClass('hidden')
  });
  $("#stop_time").click(function(event){
    alert("Great! Stop session!");
    var session_id = "<%=params[:medical_session]%>";
    $.get("/session/" + session_id + "/stop_time");
  });
</script>

app/views/medicine/drug_final_indication.html.erb
<html>
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left" href="medicine">
    <span class="icon icon-left-nav"></span>
    <a href="/medicine/<%=@drug.id%>">Back</a>
  </button>
  <button class="btn btn-link btn-nav pull-right">
    <a href="/medicine/<%=@drug.id%>/education">Education</a>
    <span class="icon icon-right-nav"></span>
  </button>
  <h1 class="title"><%= @drug.drug_name %></h1>
</header>

<div class="content">
    <button class="btn btn-block"><%= @drug.brand %></button>
    <ul class="table-view">
      <% for item in @final_indication %>
          <li class="table-view-cell media">
            <img class="media-object pull-left" src="http://placehold.it/42x42">
            <div class="media-body">
               <%= item.content%>
            </div> </li>
      <% end %>
    </ul>
  </div>
  <%= render partial: "layouts/navigation" %>
</html>

app/views/medicine/drug_indication.html.erb
<html>
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left">
    <span class="icon icon-left-nav"></span>
    <%= link_to "Back", action: "drug_list" %>
  </button>
  <button class="btn btn-link btn-nav pull-right">
    <%= link_to "Education", action: "drug_education", medical_session: params[:medical_session] %>
    <span class="icon icon-right-nav"></span>
  </button>
  <h1 class="title"><%= @drug.drug_name %></h1>
</header>

<div class="content">
    <button class="btn btn-block"><%= @drug.brand %></button>
    <ul class="table-view">
      <% for item in @indication %>
          <li class="table-view-cell media">
            <img class="media-object pull-left" src="http://placehold.it/42x42">
            <div class="media-body">
               <%= item.content%>
            </div> </li>
      <% end %>
    <% if @session.first_element?(@drug) %>
      <button id="start_time" type="submit" class="btn btn-block">Start timing the education time</button>
    <% end %>
    </ul>
  </div>
  <%= render partial: "layouts/navigation" %>
</html>
<script>
  $("#start_time").click(function(event){
    alert("Great! Time recorded!");
    var session_id = "<%=params[:medical_session]%>";
    $.get("/medicine/" + session_id + "/start_time");
  });
</script>

app/views/medicine/drug_list.html.erb
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left">
    <span class="icon icon-left-nav"></span>
    <%= link_to "Back", :controller => "physician", :action => "index" %>
  </button>
  <h1 class="title">Title</h1>
</header>
<div class="content">
<ul class="table-view">
  <%= form_tag new_session_path, id: "session", method:"post" do %>
    <input id="submit" type="submit" value="Start a Session!">
    <% for m in Medicine.all %>
    <li onclick="click_drug(this, id);" class="table-view-cell active">
        <%= m.drug_name %>
        <%= check_box_tag("medicine[#{m.id}]") %>
    </li>
    <% end %>
  <% end %>
</ul>
</div>
  <%= render partial: "layouts/navigation" %>
<script>
  $(function() {
    $('#session').data('serialize',$('#session').serialize());
  });

  function click_drug(el, id){
   inp = $(el).find("input");
   inp.prop("checked", !inp.prop("checked"));
  };

  $('li input[type=checkbox]').on("click", function(){
    $(this).prop("checked", !$(this).prop("checked"));
  });

  function formchanged(){
    form_clean = $('#session').serialize()
    if($('#session').serialize()!=$('#session').data('serialize')){
        // Form has changed!!!
        return (true);
        }
        return (false);
  }
  $('#session').submit(function(event){
    if (formchanged()==false ) {
        event.preventDefault();
        alert("Please choose a drug");
    }
  });

</script>

app/views/medicine/index.html.erb
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left">
    <span class="icon icon-left-nav"></span>
    <%= link_to "Back", :controller => "physician", :action => "index" %>
  </button>
  <h1 class="title">Title</h1>
</header>
<div class="content">
<ul class="table-view">
  <% for m in Medicine.all %>
  <li class="table-view-cell">
    <a class="navigate-right" href=<%="/medicine/#{m.id}"%>>
      Drug <%= m.id%>
    </a>
    </li>
  <% end %>
</ul>
</div>

<nav class="bar bar-tab">
  <a class="tab-item active" href="/home">
    <span class="glyphicon glyphicon-home"></span>
    <span class="tab-label">Home</span>
  </a>
  <a class="tab-item" href="medicine">
    <span class="glyphicon glyphicon-tint"></span>
    <span class="tab-label">Medicine</span>
  </a>
  <a class="tab-item" href="#">
    <span class="icon icon-search"></span>
    <span class="tab-label">Search</span>
  </a>
</nav>

app/views/medicine/show_indication.html.erb
<header class="bar bar-nav">
  <button class="btn btn-link btn-nav pull-left" href="medicine">
    <span class="icon icon-left-nav"></span>
    <%= link_to "Back", :controller => "medicine", :action => "index" %>
  </button>
  <h1 class="title"><%= @drug.drug_name %></h1>
</header>

<div class="content">
    <button class="btn btn-block"><%= @drug.brand %></button>
    <ul class="table-view">
      <% for item in @indication %>
      <li class="table-view-cell media">
        <img class="media-object pull-left" src="http://placehold.it/42x42">
        <div class="media-body">
           <%= item.content %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
<nav class="bar bar-tab">
  <a class="tab-item active" href="/home">
    <span class="glyphicon glyphicon-home"></span>
    <span class="tab-label">Home</span>
  </a>
  <a class="tab-item" href="/medicine">
    <span class="glyphicon glyphicon-tint"></span>
    <span class="tab-label">Medicine</span>
  </a>
  <a class="tab-item" href="#">
    <span class="icon icon-search"></span>
    <span class="tab-label">Search</span>
  </a>
</nav>