config/routes.rb
Medicallapp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Surveyor::Engine => "/surveys", :as => "surveyor"

  root to: 'physician#index'
  get 'home' => 'physician#index'
  get 'medicine' => 'medicine#drug_list', as: 'drug_list'
  get 'session/:medical_session/medicine/:id' => 'medicine#drug_indication'
  get 'session/:medical_session/medicine/:id/education' => 'medicine#drug_education'
  post 'session/new' => 'medicalsession#new', as: 'new_session'
  get 'session/:medical_session/start_time' => 'medicalsession#start_time', as: 'start_time'
  get 'session/:medical_session/stop_time' => 'medicalsession#stop_time', as: 'stop_time'

  post 'indication/:id' => 'indication#choose_indication'
  post 'medicine/:id/final_indication' => 'medicine#drug_final_indication', as: 'show_final_indication'

  get 'show_import' => 'physician#show_import'
  post 'import' => 'medicine#import'
   resources :medicine do
     collection { post :import }
   end

end

app/models/physicians.rb
class Physicians < ActiveRecord::Base
  attr_accessible :name, :email
  has_many :survey
end

app/controllers/physician_controller.rb
class PhysicianController < ApplicationController
  def index
  end

  def show_import
  end
end

app/helpers/physician_helper.rb
module PhysicianHelper
end

app/views/physician/index.html.erb
<html>
  <ul class="nav nav-tabs col-md-offset-1" role="tablist">
    <li>
    <a> <span class="glyphicon glyphicon-home"></span></a>
    </li>
    <li>
      <a href="#">Home</a>
    </li>
    <li>
      <a href="/medicine">Medicine List</a>
    </li>
    <li>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, class: "login_button"  %> |
        <%= link_to "Logout", destroy_user_session_path, class: "login_button", method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "login_button" %> |
        <%= link_to "Login", new_user_session_path, class: "login_button" %>
      <% end %>
  </ul>
  <%= render 'layouts/navigation' %>
</html>

app/views/physician/show_import.html.erb
<h2>Import Products</h2>

<%= form_tag import_medicine_index_path, multipart: true, action:'post' do %>
    <%= file_field_tag 'file' %>
      <%= submit_tag "Import" %>
    <% end %>
  <%= render partial: "layouts/navigation" %>